<?php
/**
 * Derive the DoughBossData.i18n map in class-doughboss-assets.php from the
 * t('key', 'fallback') call sites in public/js/doughboss.js, so the strings
 * WordPress translates are exactly the strings the storefront uses.
 *
 * Usage:
 *   php tests/gen-i18n.php          # rewrite the i18n block in place
 *   php tests/gen-i18n.php --check  # exit 1 if the block is out of date
 *
 * @package DoughBoss
 */

$root  = dirname( __DIR__ );
$js    = file_get_contents( $root . '/public/js/doughboss.js' );
$php   = $root . '/includes/class-doughboss-assets.php';
$src   = file_get_contents( $php );
$check = in_array( '--check', $argv, true );

preg_match_all( "/\\bt\\(\\s*'([A-Za-z0-9_]+)'\\s*,\\s*'((?:[^'\\\\]|\\\\.)*)'\\s*\\)/u", $js, $m, PREG_SET_ORDER );

$keys = array();
foreach ( $m as $hit ) {
	$key      = $hit[1];
	$fallback = str_replace( "\\'", "'", $hit[2] );
	if ( isset( $keys[ $key ] ) && $keys[ $key ] !== $fallback ) {
		fwrite( STDERR, "Conflicting fallbacks for '{$key}': '{$keys[ $key ]}' vs '{$fallback}'\n" );
		exit( 2 );
	}
	$keys[ $key ] = $fallback;
}
ksort( $keys );

$width = max( array_map( 'strlen', array_keys( $keys ) ) ) + 2;
$lines = array();
foreach ( $keys as $key => $fallback ) {
	$quoted  = "'" . str_replace( "'", "\\'", $fallback ) . "'";
	$lines[] = "\t\t\t\t" . str_pad( "'" . $key . "'", $width ) . "=> __( " . $quoted . ", 'doughboss' ),";
}
$block = "\t\t\t// phpcs:disable Generic.Formatting.MultipleStatementAlignment -- generated by tests/gen-i18n.php from the t() calls in doughboss.js.\n"
	. "\t\t\t'i18n'         => array(\n" . implode( "\n", $lines ) . "\n\t\t\t),\n"
	. "\t\t\t// phpcs:enable\n";

$pattern = "/\t\t\t(?:\\/\\/ phpcs:disable[^\n]*\n\t\t\t)?'i18n'\\s*=> array\\(\n.*?\n\t\t\t\\),\n(?:\t\t\t\\/\\/ phpcs:enable\n)?/s";
if ( ! preg_match( $pattern, $src ) ) {
	fwrite( STDERR, "Could not find the i18n block in {$php}\n" );
	exit( 2 );
}
$new = preg_replace( $pattern, $block, $src, 1 );

if ( $check ) {
	if ( $new !== $src ) {
		fwrite( STDERR, "i18n map is out of date: run php tests/gen-i18n.php\n" );
		exit( 1 );
	}
	echo 'i18n map up to date (' . count( $keys ) . " keys)\n";
	exit( 0 );
}

file_put_contents( $php, $new );
echo 'Wrote ' . count( $keys ) . " i18n keys to includes/class-doughboss-assets.php\n";
