<?php
$catering_email = class_exists( 'DoughBoss_Settings' ) ? DoughBoss_Settings::catering_email() : 'catering@doughboss.com.au';
$catering_phone = class_exists( 'DoughBoss_Settings' ) ? DoughBoss_Settings::catering_phone() : '0422487487';
$catering_tel   = preg_replace( '/[^0-9+]/', '', $catering_phone );
get_header();
?>
<section class="dbf-hero"><div class="dbf-wrap"><h1 class="dbf-sr-only"><?php esc_html_e( 'Dough Boss catering', 'doughboss-final' ); ?></h1><?php echo doughboss_final_shortcode_or_notice( '[doughboss_manoush_hero variant="catering" kicker="Catering, made fresh" title="Feed the whole table." description="Office runs, family gatherings, celebrations and functions — tell us what you need and we will help plan the spread." replay_label="Pause photo motion"]', __( 'Catering is being prepared.', 'doughboss-final' ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></div></section>
<section class="dbf-section dbf-section--cream"><div class="dbf-wrap dbf-feature-grid"><div data-dbf-reveal><p class="dbf-eyebrow">Made for sharing</p><h2 class="dbf-heading">Fresh food for meetings, teams and celebrations.</h2><p class="dbf-lede">Choose from mini manoush, pizzas, pies, wraps and platters. Our catering team will confirm availability, timing and the best mix for your group.</p><a class="dbf-button" href="#catering-enquiry">Contact the catering team</a></div><div class="dbf-catering-media" data-dbf-reveal data-dbf-reveal-delay="1"><img src="<?php echo esc_url( doughboss_final_asset_url( 'doughboss-feast-real-v1.jpg' ) ); ?>" width="1080" height="864" alt="A real Dough Boss catering spread" loading="lazy" decoding="async"></div></div></section>
<section id="catering-enquiry" class="dbf-section" tabindex="-1"><div class="dbf-wrap"><div class="dbf-contact-strip"><a href="<?php echo esc_url( 'mailto:' . $catering_email ); ?>"><span><?php esc_html_e( 'Catering email', 'doughboss-final' ); ?></span><?php echo esc_html( $catering_email ); ?></a><a href="<?php echo esc_url( 'tel:' . $catering_tel ); ?>"><span><?php esc_html_e( 'Call catering', 'doughboss-final' ); ?></span><?php echo esc_html( $catering_phone ); ?></a></div><div class="dbf-catering-app"><?php echo doughboss_final_shortcode_or_notice( '[doughboss_catering]', __( 'The catering enquiry form is being prepared. Please contact the catering team using the details above.', 'doughboss-final' ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></div></div></section>
<?php get_footer(); ?>
