<?php
/**
 * Front-end asset registration and localization.
 *
 * @package DoughBoss
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Enqueues the storefront CSS/JS and passes runtime config to JavaScript.
 */
class DoughBoss_Assets {

	/**
	 * Whether the storefront assets have been enqueued this request.
	 *
	 * @var bool
	 */
	private static $enqueued = false;

	/**
	 * Register hooks.
	 *
	 * @return void
	 */
	public function init() {
		add_action( 'wp_enqueue_scripts', array( $this, 'enqueue' ) );
	}

	/**
	 * Cheap early check: does this singular post's content contain any of our
	 * shortcodes? has_shortcode() rebuilds a regex from every registered
	 * shortcode on the site, so guard it with a strpos first. This is only a
	 * fast path — the shortcodes themselves enqueue on render, which covers
	 * page builders, block templates and synced patterns.
	 *
	 * @return bool
	 */
	private function should_load_early() {
		if ( is_singular() ) {
			$post = get_post();
			if ( $post instanceof WP_Post && false !== strpos( $post->post_content, '[doughboss_' ) ) {
				return true;
			}
		}

		/**
		 * Force-load the storefront assets (e.g. for a theme that renders the
		 * shortcodes from a template part).
		 *
		 * @param bool $load Whether to load.
		 */
		return (bool) apply_filters( 'doughboss_load_assets', false );
	}

	/**
	 * Enqueue styles and scripts when the early check says so.
	 *
	 * @return void
	 */
	public function enqueue() {
		if ( $this->should_load_early() ) {
			self::enqueue_now();
		}
	}

	/**
	 * Enqueue the storefront assets (idempotent). Safe to call from a
	 * shortcode callback: the script is a footer script, and WordPress prints
	 * late-enqueued styles in the footer too.
	 *
	 * @return void
	 */
	public static function enqueue_now() {
		if ( self::$enqueued ) {
			return;
		}
		self::$enqueued = true;

		wp_enqueue_style(
			'doughboss',
			DOUGHBOSS_PLUGIN_URL . 'public/css/doughboss.css',
			array(),
			DOUGHBOSS_VERSION
		);

		wp_enqueue_script(
			'doughboss',
			DOUGHBOSS_PLUGIN_URL . 'public/js/doughboss.js',
			array(),
			DOUGHBOSS_VERSION,
			true
		);

		wp_localize_script( 'doughboss', 'DoughBossData', self::script_data() );
	}

	/**
	 * The `DoughBossData` payload.
	 *
	 * The config is inlined so the builder and cart never block on a request
	 * for it. The nonce is still embedded for the common uncached case; the
	 * storefront refreshes it from GET /nonce when it has gone stale behind a
	 * full-page cache instead of failing every cart action with a 403.
	 *
	 * @return array
	 */
	private static function script_data() {
		return array(
			'restUrl'      => esc_url_raw( rest_url( DOUGHBOSS_REST_NAMESPACE ) ),
			'nonce'        => wp_create_nonce( 'wp_rest' ),
			'currency'     => DoughBoss_Settings::get( 'currency_symbol', '$' ),
			'config'       => DoughBoss_Settings::public_config(),
			'storePhone'   => (string) DoughBoss_Settings::get( 'store_phone', '' ),
			'menuUrl'      => (string) DoughBoss_Settings::get( 'menu_page_url', '' ),
			'trackingUrl'  => (string) DoughBoss_Settings::get( 'tracking_page_url', '' ),
			'headingLevel' => 2,
			// phpcs:disable Generic.Formatting.MultipleStatementAlignment -- generated by tests/gen-i18n.php from the t() calls in doughboss.js.
			'i18n'         => array(
				'addToCart'         => __( 'Add to cart', 'doughboss' ),
				'added'             => __( 'Added!', 'doughboss' ),
				'addedToCart'       => __( '{name} added to your order.', 'doughboss' ),
				'adding'            => __( 'Adding…', 'doughboss' ),
				'browseMenu'        => __( 'Browse the menu', 'doughboss' ),
				'builderHeading'    => __( 'Build your pizza', 'doughboss' ),
				'builderNoSizes'    => __( 'No pizza sizes configured yet.', 'doughboss' ),
				'callUs'            => __( 'Call us on', 'doughboss' ),
				'cartBadgeLabel'    => __( 'View cart — {count} items, {total}', 'doughboss' ),
				'checkout'          => __( 'Checkout', 'doughboss' ),
				'closedTitle'       => __( 'Online ordering is currently closed.', 'doughboss' ),
				'confirmNumber'     => __( 'Your order number is', 'doughboss' ),
				'confirmTitle'      => __( 'Thanks! Your order has been received.', 'doughboss' ),
				'decreaseQuantity'  => __( 'Decrease quantity for {name}', 'doughboss' ),
				'delivery'          => __( 'Delivery', 'doughboss' ),
				'delivery_option'   => __( 'Delivery', 'doughboss' ),
				'edit'              => __( 'Edit', 'doughboss' ),
				'editItem'          => __( 'Edit {name}', 'doughboss' ),
				'editingPizza'      => __( 'Editing your custom pizza — update it and add it back.', 'doughboss' ),
				'emptyCart'         => __( 'Your cart is empty.', 'doughboss' ),
				'errCartExpired'    => __( 'Your cart has expired. Please add your items again.', 'doughboss' ),
				'errClosed'         => __( 'Online ordering is currently closed.', 'doughboss' ),
				'errInvalidEmail'   => __( 'Please enter a valid email address.', 'doughboss' ),
				'errPricesChanged'  => __( 'Some prices changed — please review your order.', 'doughboss' ),
				'errRateLimited'    => __( 'Too many attempts, please wait a minute.', 'doughboss' ),
				'errRequiredAddress'=> __( 'Please enter your delivery address.', 'doughboss' ),
				'errRequiredEmail'  => __( 'Please enter your email address.', 'doughboss' ),
				'errRequiredName'   => __( 'Please enter your name.', 'doughboss' ),
				'errRequiredPhone'  => __( 'Please enter a phone number.', 'doughboss' ),
				'fieldAddress'      => __( 'Delivery address', 'doughboss' ),
				'fieldEmail'        => __( 'Email', 'doughboss' ),
				'fieldName'         => __( 'Name', 'doughboss' ),
				'fieldNotes'        => __( 'Notes (optional)', 'doughboss' ),
				'fieldPhone'        => __( 'Phone', 'doughboss' ),
				'fulfilment'        => __( 'How would you like your order?', 'doughboss' ),
				'genericError'      => __( 'Something went wrong. Please try again.', 'doughboss' ),
				'increaseQuantity'  => __( 'Increase quantity for {name}', 'doughboss' ),
				'menuCategories'    => __( 'Menu categories', 'doughboss' ),
				'menuEmpty'         => __( 'No menu items yet.', 'doughboss' ),
				'menuHeading'       => __( 'Menu', 'doughboss' ),
				'minOrder'          => __( 'Minimum order {amount}', 'doughboss' ),
				'noToppings'        => __( 'No toppings', 'doughboss' ),
				'orderLabel'        => __( 'Order', 'doughboss' ),
				'pickup'            => __( 'Pickup', 'doughboss' ),
				'placeOrder'        => __( 'Place order', 'doughboss' ),
				'placing'           => __( 'Placing order…', 'doughboss' ),
				'printReceipt'      => __( 'Print receipt', 'doughboss' ),
				'quantityFor'       => __( 'Quantity for {name}', 'doughboss' ),
				'questionsCall'     => __( 'Questions? Call', 'doughboss' ),
				'recentOrder'       => __( 'Your recent order', 'doughboss' ),
				'remove'            => __( 'Remove', 'doughboss' ),
				'removeItem'        => __( 'Remove {name} from cart', 'doughboss' ),
				'removedItem'       => __( '{name} removed.', 'doughboss' ),
				'restored'          => __( '{name} put back in your order.', 'doughboss' ),
				'retry'             => __( 'Try again', 'doughboss' ),
				'size'              => __( 'Size', 'doughboss' ),
				'soldOut'           => __( 'Sold out', 'doughboss' ),
				'soldOutNote'       => __( 'This item is unavailable right now.', 'doughboss' ),
				'subtotal'          => __( 'Subtotal', 'doughboss' ),
				'taxIncluded'       => __( 'Includes {label} {amount}', 'doughboss' ),
				'toppings'          => __( 'Toppings', 'doughboss' ),
				'total'             => __( 'Total', 'doughboss' ),
				'totalDueDelivery'  => __( 'Total due on delivery', 'doughboss' ),
				'totalDuePickup'    => __( 'Total due on pickup', 'doughboss' ),
				'trackEmail'        => __( 'Email', 'doughboss' ),
				'trackHeading'      => __( 'Track your order', 'doughboss' ),
				'trackIt'           => __( 'Track it', 'doughboss' ),
				'trackNumber'       => __( 'Order number', 'doughboss' ),
				'trackOrder'        => __( 'Track your order', 'doughboss' ),
				'trackSearching'    => __( 'Looking up your order…', 'doughboss' ),
				'trackSubmit'       => __( 'Find my order', 'doughboss' ),
				'undo'              => __( 'Undo', 'doughboss' ),
				'updatePizza'       => __( 'Update pizza', 'doughboss' ),
				'yourOrder'         => __( 'Your order', 'doughboss' ),
			),
			// phpcs:enable
		);
	}
}
